# Utiliser l'image Ubuntu comme base
FROM ubuntu:latest

# Mettre à jour les paquets et installer openssh-server
RUN apt-get update && apt-get install -y openssh-server sudo

# Créer le répertoire nécessaire au bon fonctionnement du service SSH
RUN mkdir /var/run/sshd

# Ajouter le mot de passe 'root123' pour le compte root
RUN echo 'root:root123' | chpasswd

# Modifier la configuration SSH pour permettre la connexion root
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Exposer le port 2222 pour SSH
EXPOSE 2222

# Lancer le service SSH en mode "foreground" pour qu'il continue à tourner dans le conteneur
CMD ["/usr/sbin/sshd", "-D"]
